### PR TITLE
Modernize the error-prone-checks repository

### PR DESCRIPTION
**Pull request by ksobolew**
* Base on a newer version of aribase
* Upgrade some dependencies
* Upgrade Error Prone
* Switch from TestNG to JUnit5

### CODE REVIEW

**Review by kokosing — APPROVED** [review]

**Comment by ksobolew** [comment]
Well obviously I forgot to update the CI scripts ;)

**Comment by ksobolew** [comment]
@kokosing do you know where this `build (17)` comes from? Apparently it's waiting for `ci / build (17)` which does not exist anymore (replaced by `ci / build (21)`).

**Comment by kokosing** [comment]
It comes from the settings of repo. I will update settings.

**Comment by kokosing** [comment]
Done.

**Pull request merged**
